/*
 * generated by Xtext 2.16.0
 */
package at.ac.univie.swa


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CmlRuntimeModule extends AbstractCmlRuntimeModule {
}
