/*
 * generated by Xtext 2.16.0
 */
package at.ac.univie.swa


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CmlStandaloneSetup extends CmlStandaloneSetupGenerated {

	def static void doSetup() {
		new CmlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
