/*
 * generated by Xtext 2.17.1
 */
package at.ac.univie.swa.ide

import at.ac.univie.swa.CmlRuntimeModule
import at.ac.univie.swa.CmlStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class CmlIdeSetup extends CmlStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new CmlRuntimeModule, new CmlIdeModule))
	}
	
}
